[theme]
description = "my_theme"

[colors]
[colors.body]
r = 0.82
g = 0.82
b = 0.82

[colors.neck]
r = 0.82
g = 0.82
b = 0.82

[colors.head]
r = 0.82
g = 0.82
b = 0.82

[colors.beak]
r = 1.0
g = 0.6
b = 0.0

[colors.eye]
r = 0.1
g = 0.1
b = 0.1

[colors.outline]
r = 0.82
g = 0.82
b = 0.82


