// AUTO-GENERATED by tools/generate_config.py - DO NOT EDIT
#import "config_gui.h"

@implementation ConfigGUI (Generated)

- (void)addGeneratedRows {

    // === Debug ===
    [self addRow:@"to_terminal" label:@"To Terminal" type:@(ConfigTypeBool) boolPtr:&g_config.toTerminal];
    [self addRow:@"visuals" label:@"Visuals" type:@(ConfigTypeBool) boolPtr:&g_config.visuals];

    // === General ===
    [self addRow:@"global_scale" label:@"Global Scale" type:@(ConfigTypeFloat) floatPtr:&g_config.globalScale min:@(0.0f) max:@(10.0f) step:@(0.1f)];
    [self addRow:@"audio_enabled" label:@"Audio Enabled" type:@(ConfigTypeBool) boolPtr:&g_config.audioEnabled];
    [self addRow:@"audio_muted" label:@"Audio Muted" type:@(ConfigTypeBool) boolPtr:&g_config.audioMuted];
    [self addRow:@"memes_enabled" label:@"Memes Enabled" type:@(ConfigTypeBool) boolPtr:&g_config.memesEnabled];
    [self addRow:@"appearance_mode" label:@"Appearance Mode" type:@(ConfigTypeInt) intPtr:&g_config.appearanceMode min:@(0) max:@(3)];
    [self addRow:@"light_theme_role" label:@"Light Theme Role" type:@(ConfigTypeString) stringPtr:&g_config.lightThemeRole];
    [self addRow:@"dark_theme_role" label:@"Dark Theme Role" type:@(ConfigTypeString) stringPtr:&g_config.darkThemeRole];
    [self addRow:@"failsafe_hotkey" label:@"Failsafe Hotkey" type:@(ConfigTypeString) stringPtr:&g_config.failsafeHotkey];

    // === Screen ===
    [self addRow:@"default_width" label:@"Default Width" type:@(ConfigTypeInt) intPtr:&g_config.defaultWidth min:@(0) max:@(10000)];
    [self addRow:@"default_height" label:@"Default Height" type:@(ConfigTypeInt) intPtr:&g_config.defaultHeight min:@(0) max:@(10000)];

    // === Asset ===
    [self addRow:@"meme_placeholder_w" label:@"Meme Placeholder W" type:@(ConfigTypeInt) intPtr:&g_config.memePlaceholderW min:@(0) max:@(1000)];
    [self addRow:@"meme_placeholder_h" label:@"Meme Placeholder H" type:@(ConfigTypeInt) intPtr:&g_config.memePlaceholderH min:@(0) max:@(1000)];
    [self addRow:@"text_placeholder_w" label:@"Text Placeholder W" type:@(ConfigTypeInt) intPtr:&g_config.textPlaceholderW min:@(0) max:@(1000)];
    [self addRow:@"text_placeholder_h" label:@"Text Placeholder H" type:@(ConfigTypeInt) intPtr:&g_config.textPlaceholderH min:@(0) max:@(1000)];
    [self addRow:@"note_placeholder_w" label:@"Note Placeholder W" type:@(ConfigTypeInt) intPtr:&g_config.notePlaceholderW min:@(0) max:@(1000)];
    [self addRow:@"note_placeholder_h" label:@"Note Placeholder H" type:@(ConfigTypeInt) intPtr:&g_config.notePlaceholderH min:@(0) max:@(1000)];

    // === Cursor ===
    [self addRow:@"chase_enabled" label:@"Chase Enabled" type:@(ConfigTypeBool) boolPtr:&g_config.chaseEnabled];
    [self addRow:@"chase_chance" label:@"Chase Chance" type:@(ConfigTypeInt) intPtr:&g_config.chaseChance min:@(0) max:@(100)];
    [self addRow:@"multi_monitor_enabled" label:@"Multi Monitor Enabled" type:@(ConfigTypeBool) boolPtr:&g_config.multiMonitorEnabled];

    // === Movement ===
    [self addRow:@"base_walk_speed" label:@"Base Walk Speed" type:@(ConfigTypeFloat) floatPtr:&g_config.baseWalkSpeed min:@(0.0f) max:@(1000.0f) step:@(0.1f)];
    [self addRow:@"base_run_speed" label:@"Base Run Speed" type:@(ConfigTypeFloat) floatPtr:&g_config.baseRunSpeed min:@(0.0f) max:@(1000.0f) step:@(0.1f)];
    [self addRow:@"max_force" label:@"Max Force" type:@(ConfigTypeFloat) floatPtr:&g_config.maxForce min:@(0.0f) max:@(1000.0f) step:@(0.1f)];
    [self addRow:@"move_distance_threshold" label:@"Move Distance Threshold" type:@(ConfigTypeFloat) floatPtr:&g_config.moveDistanceThreshold min:@(0.0f) max:@(1000.0f) step:@(0.1f)];
    [self addRow:@"friction" label:@"Friction" type:@(ConfigTypeFloat) floatPtr:&g_config.friction min:@(0.0f) max:@(1000.0f) step:@(0.1f)];
    [self addRow:@"max_speed" label:@"Max Speed" type:@(ConfigTypeFloat) floatPtr:&g_config.maxSpeed min:@(0.0f) max:@(1000.0f) step:@(0.1f)];
    [self addRow:@"run_speed_multiplier" label:@"Run Speed Multiplier" type:@(ConfigTypeFloat) floatPtr:&g_config.runSpeedMultiplier min:@(0.0f) max:@(10.0f) step:@(0.1f)];
    [self addRow:@"init_direction_max" label:@"Init Direction Max" type:@(ConfigTypeFloat) floatPtr:&g_config.initDirectionMax min:@(0.0f) max:@(360.0f) step:@(1.0f)];
    [self addRow:@"speed_lerp_rate" label:@"Speed Lerp Rate" type:@(ConfigTypeFloat) floatPtr:&g_config.speedLerpRate min:@(0.0f) max:@(1.0f) step:@(0.01f)];
    [self addRow:@"arrival_radius" label:@"Arrival Radius" type:@(ConfigTypeFloat) floatPtr:&g_config.arrivalRadius min:@(0.0f) max:@(1000.0f) step:@(1.0f)];
    [self addRow:@"run_distance_threshold" label:@"Run Distance Threshold" type:@(ConfigTypeFloat) floatPtr:&g_config.runDistanceThreshold min:@(0.0f) max:@(2000.0f) step:@(1.0f)];
    [self addRow:@"direction_blend_rate" label:@"Direction Blend Rate" type:@(ConfigTypeFloat) floatPtr:&g_config.directionBlendRate min:@(0.0f) max:@(1.0f) step:@(0.01f)];

    // === Physics ===
    [self addRow:@"screen_margin" label:@"Screen Margin" type:@(ConfigTypeFloat) floatPtr:&g_config.screenMargin min:@(0.0f) max:@(500.0f) step:@(1.0f)];
    [self addRow:@"bounce_factor_wall" label:@"Bounce Factor Wall" type:@(ConfigTypeFloat) floatPtr:&g_config.bounceFactorWall min:@(0.0f) max:@(2.0f) step:@(0.1f)];
    [self addRow:@"bounce_factor_corner" label:@"Bounce Factor Corner" type:@(ConfigTypeFloat) floatPtr:&g_config.bounceFactorCorner min:@(0.0f) max:@(2.0f) step:@(0.1f)];
    [self addRow:@"corner_margin" label:@"Corner Margin" type:@(ConfigTypeFloat) floatPtr:&g_config.cornerMargin min:@(0.0f) max:@(500.0f) step:@(1.0f)];
    [self addRow:@"drag_min_dt" label:@"Drag Min Dt" type:@(ConfigTypeFloat) floatPtr:&g_config.dragMinDt min:@(0.0f) max:@(1.0f) step:@(0.01f)];
    [self addRow:@"drag_velocity_threshold" label:@"Drag Velocity Threshold" type:@(ConfigTypeFloat) floatPtr:&g_config.dragVelocityThreshold min:@(0.0f) max:@(1000.0f) step:@(1.0f)];
    [self addRow:@"drag_rotation_speed" label:@"Drag Rotation Speed" type:@(ConfigTypeFloat) floatPtr:&g_config.dragRotationSpeed min:@(0.0f) max:@(10.0f) step:@(0.1f)];
    [self addRow:@"iso_scale_x" label:@"Iso Scale X" type:@(ConfigTypeFloat) floatPtr:&g_config.isoScaleX min:@(0.1f) max:@(2.0f) step:@(0.01f)];
    [self addRow:@"iso_scale_y" label:@"Iso Scale Y" type:@(ConfigTypeFloat) floatPtr:&g_config.isoScaleY min:@(0.1f) max:@(2.0f) step:@(0.01f)];
    [self addRow:@"edge_avoid_margin" label:@"Edge Avoid Margin" type:@(ConfigTypeFloat) floatPtr:&g_config.edgeAvoidMargin min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"edge_look_ahead_speed" label:@"Edge Look Ahead Speed" type:@(ConfigTypeFloat) floatPtr:&g_config.edgeLookAheadSpeed min:@(0.0f) max:@(1.0f) step:@(0.01f)];
    [self addRow:@"edge_look_ahead_base" label:@"Edge Look Ahead Base" type:@(ConfigTypeFloat) floatPtr:&g_config.edgeLookAheadBase min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"edge_avoid_force" label:@"Edge Avoid Force" type:@(ConfigTypeFloat) floatPtr:&g_config.edgeAvoidForce min:@(0.0f) max:@(10.0f) step:@(0.1f)];
    [self addRow:@"screen_clamp_tight" label:@"Screen Clamp Tight" type:@(ConfigTypeFloat) floatPtr:&g_config.screenClampTight min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"screen_clamp_expanded" label:@"Screen Clamp Expanded" type:@(ConfigTypeFloat) floatPtr:&g_config.screenClampExpanded min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"screen_clamp_bounce" label:@"Screen Clamp Bounce" type:@(ConfigTypeFloat) floatPtr:&g_config.screenClampBounce min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"steer_seek_force" label:@"Steer Seek Force" type:@(ConfigTypeFloat) floatPtr:&g_config.steerSeekForce min:@(0.0f) max:@(20.0f) step:@(0.1f)];
    [self addRow:@"curve_fade_distance" label:@"Curve Fade Distance" type:@(ConfigTypeFloat) floatPtr:&g_config.curveFadeDistance min:@(0.0f) max:@(1000.0f) step:@(1.0f)];
    [self addRow:@"curve_tangent_force" label:@"Curve Tangent Force" type:@(ConfigTypeFloat) floatPtr:&g_config.curveTangentForce min:@(0.0f) max:@(5.0f) step:@(0.1f)];
    [self addRow:@"curve_fade_min_vel" label:@"Curve Fade Min Vel" type:@(ConfigTypeFloat) floatPtr:&g_config.curveFadeMinVel min:@(0.0f) max:@(100.0f) step:@(1.0f)];
    [self addRow:@"direction_rotate_min_vel" label:@"Direction Rotate Min Vel" type:@(ConfigTypeFloat) floatPtr:&g_config.directionRotateMinVel min:@(0.0f) max:@(100.0f) step:@(1.0f)];
    [self addRow:@"direction_to_cursor_dist" label:@"Direction To Cursor Dist" type:@(ConfigTypeFloat) floatPtr:&g_config.directionToCursorDist min:@(0.0f) max:@(10.0f) step:@(0.1f)];
    [self addRow:@"snap_distance" label:@"Snap Distance" type:@(ConfigTypeFloat) floatPtr:&g_config.snapDistance min:@(0.0f) max:@(10.0f) step:@(0.1f)];
    [self addRow:@"direction_reverse_multiplier" label:@"Direction Reverse Multiplier" type:@(ConfigTypeFloat) floatPtr:&g_config.directionReverseMultiplier min:@(-1.0f) max:@(1.0f) step:@(0.1f)];
    [self addRow:@"min_valid_scale" label:@"Min Valid Scale" type:@(ConfigTypeFloat) floatPtr:&g_config.minValidScale min:@(0.0f) max:@(1.0f) step:@(0.01f)];

    // === Spawn ===
    [self addRow:@"margin_x" label:@"Margin X" type:@(ConfigTypeFloat) floatPtr:&g_config.marginX min:@(0.0f) max:@(1000.0f) step:@(1.0f)];
    [self addRow:@"margin_y" label:@"Margin Y" type:@(ConfigTypeFloat) floatPtr:&g_config.marginY min:@(0.0f) max:@(1000.0f) step:@(1.0f)];
    [self addRow:@"target_reached_threshold_return" label:@"Target Reached Threshold Return" type:@(ConfigTypeFloat) floatPtr:&g_config.targetReachedThresholdReturn min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"target_reached_threshold_normal" label:@"Target Reached Threshold Normal" type:@(ConfigTypeFloat) floatPtr:&g_config.targetReachedThresholdNormal min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"item_pickup_distance" label:@"Item Pickup Distance" type:@(ConfigTypeFloat) floatPtr:&g_config.itemPickupDistance min:@(0.0f) max:@(100.0f) step:@(1.0f)];
    [self addRow:@"fetch_edge_margin" label:@"Fetch Edge Margin" type:@(ConfigTypeFloat) floatPtr:&g_config.fetchEdgeMargin min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"separation_max_distance" label:@"Separation Max Distance" type:@(ConfigTypeFloat) floatPtr:&g_config.separationMaxDistance min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"separation_force_multiplier" label:@"Separation Force Multiplier" type:@(ConfigTypeFloat) floatPtr:&g_config.separationForceMultiplier min:@(0.0f) max:@(5.0f) step:@(0.1f)];

    // === Rig ===
    [self addRow:@"body_y" label:@"Body Y" type:@(ConfigTypeFloat) floatPtr:&g_config.bodyY min:@(0.0f) max:@(50.0f) step:@(1.0f)];
    [self addRow:@"neck_height_idle" label:@"Neck Height Idle" type:@(ConfigTypeFloat) floatPtr:&g_config.neckHeightIdle min:@(0.0f) max:@(50.0f) step:@(1.0f)];
    [self addRow:@"neck_height_moving" label:@"Neck Height Moving" type:@(ConfigTypeFloat) floatPtr:&g_config.neckHeightMoving min:@(0.0f) max:@(50.0f) step:@(1.0f)];
    [self addRow:@"beak_len" label:@"Beak Length" type:@(ConfigTypeFloat) floatPtr:&g_config.beakLen min:@(0.0f) max:@(30.0f) step:@(1.0f)];
    [self addRow:@"beak_width" label:@"Beak Width" type:@(ConfigTypeFloat) floatPtr:&g_config.beakWidth min:@(0.0f) max:@(30.0f) step:@(1.0f)];
    [self addRow:@"stride_max" label:@"Stride Max" type:@(ConfigTypeFloat) floatPtr:&g_config.strideMax min:@(0.0f) max:@(30.0f) step:@(1.0f)];
    [self addRow:@"step_lift_height" label:@"Step Lift Height" type:@(ConfigTypeFloat) floatPtr:&g_config.stepLiftHeight min:@(0.0f) max:@(20.0f) step:@(1.0f)];

    // === Snatch ===
    [self addRow:@"radius_base" label:@"Radius Base" type:@(ConfigTypeFloat) floatPtr:&g_config.radiusBase min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"radius_range" label:@"Radius Range" type:@(ConfigTypeFloat) floatPtr:&g_config.radiusRange min:@(0.0f) max:@(200.0f) step:@(1.0f)];
    [self addRow:@"angular_speed_base" label:@"Angular Speed Base" type:@(ConfigTypeFloat) floatPtr:&g_config.angularSpeedBase min:@(0.0f) max:@(10.0f) step:@(0.1f)];
    [self addRow:@"duration" label:@"Duration" type:@(ConfigTypeFloat) floatPtr:&g_config.duration min:@(0.0f) max:@(10.0f) step:@(0.1f)];
    [self addRow:@"pull_distance" label:@"Pull Distance" type:@(ConfigTypeFloat) floatPtr:&g_config.pullDistance min:@(0.0f) max:@(300.0f) step:@(1.0f)];

    // === Mud ===
    [self addRow:@"mud_enabled" label:@"Mud Enabled" type:@(ConfigTypeBool) boolPtr:&g_config.enabled];
    [self addRow:@"mud_chance" label:@"Mud Chance" type:@(ConfigTypeInt) intPtr:&g_config.chance min:@(0) max:@(100)];
    [self addRow:@"mud_lifetime" label:@"Mud Lifetime" type:@(ConfigTypeFloat) floatPtr:&g_config.lifetime min:@(0.0f) max:@(60.0f) step:@(1.0f)];

    // === Honk ===
    [self addRow:@"honk_min_gap" label:@"Honk Min Gap" type:@(ConfigTypeFloat) floatPtr:&g_config.minGap min:@(0.0f) max:@(5.0f) step:@(0.1f)];
    [self addRow:@"honk_idle_min" label:@"Honk Idle Min" type:@(ConfigTypeFloat) floatPtr:&g_config.idleMin min:@(0.0f) max:@(30.0f) step:@(1.0f)];
    [self addRow:@"honk_idle_max" label:@"Honk Idle Max" type:@(ConfigTypeFloat) floatPtr:&g_config.idleMax min:@(0.0f) max:@(60.0f) step:@(1.0f)];
    [self addRow:@"honk_chase_cooldown" label:@"Honk Chase Cooldown" type:@(ConfigTypeFloat) floatPtr:&g_config.chaseCooldown min:@(0.0f) max:@(5.0f) step:@(0.1f)];

    // === Step ===
    [self addRow:@"step_time_fetch" label:@"Step Time Fetch" type:@(ConfigTypeFloat) floatPtr:&g_config.timeFetch min:@(0.0f) max:@(1.0f) step:@(0.01f)];
    [self addRow:@"step_time_wander" label:@"Step Time Wander" type:@(ConfigTypeFloat) floatPtr:&g_config.timeWander min:@(0.0f) max:@(1.0f) step:@(0.01f)];
    [self addRow:@"step_duration_walk" label:@"Step Duration Walk" type:@(ConfigTypeFloat) floatPtr:&g_config.durationWalk min:@(0.0f) max:@(1.0f) step:@(0.01f)];
    [self addRow:@"step_duration_run" label:@"Step Duration Run" type:@(ConfigTypeFloat) floatPtr:&g_config.durationRun min:@(0.0f) max:@(1.0f) step:@(0.01f)];
    [self addRow:@"step_lift_walk" label:@"Step Lift Walk" type:@(ConfigTypeFloat) floatPtr:&g_config.liftWalk min:@(0.0f) max:@(20.0f) step:@(1.0f)];
    [self addRow:@"step_lift_run" label:@"Step Lift Run" type:@(ConfigTypeFloat) floatPtr:&g_config.liftRun min:@(0.0f) max:@(20.0f) step:@(1.0f)];

    // === Item ===
    [self addRow:@"item_pickup_cooldown" label:@"Item Pickup Cooldown" type:@(ConfigTypeFloat) floatPtr:&g_config.pickupCooldown min:@(0.0f) max:@(10.0f) step:@(0.1f)];
    [self addRow:@"item_lifetime" label:@"Item Lifetime" type:@(ConfigTypeFloat) floatPtr:&g_config.itemLifetime min:@(0.0f) max:@(120.0f) step:@(1.0f)];
    [self addRow:@"meme_lifetime" label:@"Meme Lifetime" type:@(ConfigTypeFloat) floatPtr:&g_config.memeLifetime min:@(0.0f) max:@(120.0f) step:@(1.0f)];
    [self addRow:@"text_lifetime" label:@"Text Lifetime" type:@(ConfigTypeFloat) floatPtr:&g_config.textLifetime min:@(0.0f) max:@(120.0f) step:@(1.0f)];
    [self addRow:@"max_dropped_memes" label:@"Max Dropped Memes" type:@(ConfigTypeInt) intPtr:&g_config.maxDroppedMemes min:@(0) max:@(100)];
    [self addRow:@"max_dropped_texts" label:@"Max Dropped Texts" type:@(ConfigTypeInt) intPtr:&g_config.maxDroppedTexts min:@(0) max:@(100)];
    [self addRow:@"item_fetch_cooldown" label:@"Item Fetch Cooldown" type:@(ConfigTypeFloat) floatPtr:&g_config.fetchCooldown min:@(0.0f) max:@(30.0f) step:@(1.0f)];

    // === Render ===
    [self addRow:@"shadow_offset_x" label:@"Shadow Offset X" type:@(ConfigTypeFloat) floatPtr:&g_config.shadowOffsetX min:@(-20.0f) max:@(20.0f) step:@(1.0f)];
    [self addRow:@"shadow_offset_y" label:@"Shadow Offset Y" type:@(ConfigTypeFloat) floatPtr:&g_config.shadowOffsetY min:@(0.0f) max:@(50.0f) step:@(1.0f)];
    [self addRow:@"shadow_width" label:@"Shadow Width" type:@(ConfigTypeFloat) floatPtr:&g_config.shadowWidth min:@(0.0f) max:@(100.0f) step:@(1.0f)];
    [self addRow:@"shadow_height" label:@"Shadow Height" type:@(ConfigTypeFloat) floatPtr:&g_config.shadowHeight min:@(0.0f) max:@(100.0f) step:@(1.0f)];
    [self addRow:@"foot_size" label:@"Foot Size" type:@(ConfigTypeFloat) floatPtr:&g_config.footSize min:@(0.0f) max:@(30.0f) step:@(1.0f)];
    [self addRow:@"body_width" label:@"Body Width" type:@(ConfigTypeFloat) floatPtr:&g_config.bodyWidth min:@(0.0f) max:@(50.0f) step:@(1.0f)];
    [self addRow:@"body_height" label:@"Body Height" type:@(ConfigTypeFloat) floatPtr:&g_config.bodyHeight min:@(0.0f) max:@(50.0f) step:@(1.0f)];
    [self addRow:@"neck_size" label:@"Neck Size" type:@(ConfigTypeFloat) floatPtr:&g_config.neckSize min:@(0.0f) max:@(30.0f) step:@(1.0f)];
    [self addRow:@"head1_size" label:@"Head 1 Size" type:@(ConfigTypeFloat) floatPtr:&g_config.head1Size min:@(0.0f) max:@(30.0f) step:@(1.0f)];
    [self addRow:@"head2_size" label:@"Head 2 Size" type:@(ConfigTypeFloat) floatPtr:&g_config.head2Size min:@(0.0f) max:@(30.0f) step:@(1.0f)];
    [self addRow:@"eye_size" label:@"Eye Size" type:@(ConfigTypeFloat) floatPtr:&g_config.eyeSize min:@(0.0f) max:@(20.0f) step:@(1.0f)];
    [self addRow:@"click_radius" label:@"Click Radius" type:@(ConfigTypeFloat) floatPtr:&g_config.clickRadius min:@(0.0f) max:@(100.0f) step:@(1.0f)];
    [self addRow:@"footprint_width" label:@"Footprint Width" type:@(ConfigTypeFloat) floatPtr:&g_config.footprintWidth min:@(0.0f) max:@(30.0f) step:@(1.0f)];
    [self addRow:@"footprint_height" label:@"Footprint Height" type:@(ConfigTypeFloat) floatPtr:&g_config.footprintHeight min:@(0.0f) max:@(30.0f) step:@(1.0f)];
    [self addRow:@"close_button_size" label:@"Close Button Size" type:@(ConfigTypeFloat) floatPtr:&g_config.closeButtonSize min:@(0.0f) max:@(50.0f) step:@(1.0f)];
    [self addRow:@"text_note_font_size" label:@"Text Note Font Size" type:@(ConfigTypeFloat) floatPtr:&g_config.textNoteFontSize min:@(0.0f) max:@(48.0f) step:@(1.0f)];
    [self addRow:@"squash_factor" label:@"Squash Factor" type:@(ConfigTypeFloat) floatPtr:&g_config.squashFactor min:@(0.5f) max:@(1.0f) step:@(0.01f)];
}

@end
