#!/usr/bin/env python3
"""
CadGoose Config Code Generator

Reads config_schema.yaml and generates:
  - src/common/config_registry_generated.cpp (registry entries)
  - src/platform/macos/config_gui_generated.mm (GUI rows)

Usage: python3 tools/generate_config.py tools/config_schema.yaml
"""

import sys
import yaml
import os

def snake_to_camel(name):
    """Convert snake_case to camelCase."""
    parts = name.split('_')
    return parts[0] + ''.join(p.capitalize() for p in parts[1:])

def get_struct_path(section_name, field_name):
    """Map section + field to config struct path."""
    section_map = {
        'Debug': ('debug', ''),
        'General': ('general', ''),
        'Screen': ('screen', ''),
        'Asset': ('asset', ''),
        'Cursor': ('cursor', ''),
        'Movement': ('movement', ''),
        'Physics': ('physics', ''),
        'Spawn': ('spawn', ''),
        'Rig': ('rig', ''),
        'Snatch': ('snatch', ''),
        'Mud': ('mud', ''),
        'Honk': ('honk', ''),
        'Step': ('step', ''),
        'Item': ('item', ''),
        'Render': ('render', ''),
        'Color': ('color', ''),
    }
    struct_prefix, _ = section_map.get(section_name, ('', ''))
    return f'g_config.{struct_prefix}.{field_name}'

def generate_registry_entry(field, struct_path, section_name):
    """Generate a single CONFIG_* registry entry."""
    name = field['name']
    key = field['key']
    label = field['label']
    typ = field['type']
    explanation = field.get('explanation', '')
    min_val = field.get('min', 0)
    max_val = field.get('max', 1000)
    step = field.get('step', 1)

    ptr = f'&{struct_path}'

    if typ == 'bool':
        if explanation:
            return f'    r.push_back(CONFIG_BOOL_EX("{section_name}", "{key}", "{label}",\n        "{explanation}",\n        {ptr}, OnConfigChange));'
        else:
            return f'    r.push_back(CONFIG_BOOL("{section_name}", "{key}", "{label}",\n        {ptr}, OnConfigChange));'
    elif typ == 'int':
        if explanation:
            return f'    r.push_back(CONFIG_INT_EX("{section_name}", "{key}", "{label}",\n        "{explanation}",\n        {ptr}, {min_val}, {max_val}, OnConfigChange));'
        else:
            return f'    r.push_back(CONFIG_INT("{section_name}", "{key}", "{label}",\n        {ptr}, {min_val}, {max_val}, OnConfigChange));'
    elif typ == 'float':
        if explanation:
            return f'    r.push_back(CONFIG_FLOAT_EX("{section_name}", "{key}", "{label}",\n        "{explanation}",\n        {ptr}, {min_val}f, {max_val}f, {step}f, OnConfigChange));'
        else:
            return f'    r.push_back(CONFIG_FLOAT("{section_name}", "{key}", "{label}",\n        {ptr}, {min_val}f, {max_val}f, {step}f, OnConfigChange));'
    elif typ == 'string':
        return f'    r.push_back(CONFIG_STRING("{section_name}", "{key}", "{label}",\n        {ptr}, OnConfigChange));'
    return ''

def generate_gui_row(field, struct_path):
    """Generate a single GUI addRow: call."""
    name = field['name']
    key = field['key']
    label = field['label']
    typ = field['type']
    min_val = field.get('min', 0)
    max_val = field.get('max', 1000)
    step = field.get('step', 1)

    ptr = f'&g_config.{struct_path.split(".")[-1]}'  # Just the field name for GUI

    if typ == 'bool':
        return f'    [self addRow:@"{key}" label:@"{label}" type:@(ConfigTypeBool) boolPtr:{ptr}];'
    elif typ == 'int':
        return f'    [self addRow:@"{key}" label:@"{label}" type:@(ConfigTypeInt) intPtr:{ptr} min:@({min_val}) max:@({max_val})];'
    elif typ == 'float':
        return f'    [self addRow:@"{key}" label:@"{label}" type:@(ConfigTypeFloat) floatPtr:{ptr} min:@({min_val}f) max:@({max_val}f) step:@({step}f)];'
    elif typ == 'string':
        return f'    [self addRow:@"{key}" label:@"{label}" type:@(ConfigTypeString) stringPtr:{ptr}];'
    return ''

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_config.py <schema.yaml>")
        sys.exit(1)

    schema_path = sys.argv[1]
    with open(schema_path, 'r') as f:
        schema = yaml.safe_load(f)

    output_dir = os.path.dirname(os.path.dirname(schema_path))
    project_root = os.path.dirname(output_dir)

    # Generate registry file
    registry_lines = [
        '// AUTO-GENERATED by tools/generate_config.py - DO NOT EDIT',
        '#include "config.h"',
        '',
        'void Config_RegisterGeneratedOptions(std::vector<ConfigOption>& r) {',
    ]

    gui_lines = [
        '// AUTO-GENERATED by tools/generate_config.py - DO NOT EDIT',
        '#import "config_gui.h"',
        '',
        '@implementation ConfigGUI (Generated)',
        '',
        '- (void)addGeneratedRows {',
    ]

    for section_name, section_data in schema.get('sections', {}).items():
        fields = section_data.get('fields', [])
        if not fields:
            continue

        registry_lines.append(f'')
        registry_lines.append(f'    // === {section_name} ===')
        for field in fields:
            struct_path = get_struct_path(section_name, field['name'])
            entry = generate_registry_entry(field, struct_path, section_name)
            registry_lines.append(entry)

        gui_lines.append(f'')
        gui_lines.append(f'    // === {section_name} ===')
        for field in fields:
            struct_path = get_struct_path(section_name, field['name'])
            row = generate_gui_row(field, struct_path)
            gui_lines.append(row)

    registry_lines.append('}')
    registry_lines.append('')
    gui_lines.append('}')
    gui_lines.append('')
    gui_lines.append('@end')

    # Write registry file
    registry_path = os.path.join(project_root, 'src/common/config_registry_generated.cpp')
    with open(registry_path, 'w') as f:
        f.write('\n'.join(registry_lines) + '\n')
    print(f"Generated: {registry_path}")

    # Write GUI file
    gui_path = os.path.join(project_root, 'src/platform/macos/config_gui_generated.mm')
    with open(gui_path, 'w') as f:
        f.write('\n'.join(gui_lines) + '\n')
    print(f"Generated: {gui_path}")

if __name__ == '__main__':
    main()
