// AUTO-GENERATED by tools/generate_config.py - DO NOT EDIT
#include "config.h"

void Config_RegisterGeneratedOptions(std::vector<ConfigOption>& r) {

    // === Debug ===
    r.push_back(CONFIG_BOOL("Debug", "to_terminal", "To Terminal",
        &g_config.debug.toTerminal, OnConfigChange));
    r.push_back(CONFIG_BOOL("Debug", "visuals", "Visuals",
        &g_config.debug.visuals, OnConfigChange));

    // === General ===
    r.push_back(CONFIG_FLOAT_EX("General", "global_scale", "Global Scale",
        "Multiplier for goose size and speeds (0.1 - 10.0)",
        &g_config.general.globalScale, 0.0f, 10.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_BOOL_EX("General", "audio_enabled", "Audio Enabled",
        "Play honk sounds when goose moves",
        &g_config.general.audioEnabled, OnConfigChange));
    r.push_back(CONFIG_BOOL("General", "audio_muted", "Audio Muted",
        &g_config.general.audioMuted, OnConfigChange));
    r.push_back(CONFIG_BOOL_EX("General", "memes_enabled", "Memes Enabled",
        "Allow picking up images and text as items",
        &g_config.general.memesEnabled, OnConfigChange));
    r.push_back(CONFIG_INT_EX("General", "appearance_mode", "Appearance Mode",
        "0=Light, 1=Dark, 2=System (follow macOS), 3=Custom",
        &g_config.general.appearanceMode, 0, 3, OnConfigChange));
    r.push_back(CONFIG_STRING("General", "light_theme_role", "Light Theme Role",
        &g_config.general.lightThemeRole, OnConfigChange));
    r.push_back(CONFIG_STRING("General", "dark_theme_role", "Dark Theme Role",
        &g_config.general.darkThemeRole, OnConfigChange));
    r.push_back(CONFIG_STRING("General", "failsafe_hotkey", "Failsafe Hotkey",
        &g_config.general.failsafeHotkey, OnConfigChange));

    // === Screen ===
    r.push_back(CONFIG_INT("Screen", "default_width", "Default Width",
        &g_config.screen.defaultWidth, 0, 10000, OnConfigChange));
    r.push_back(CONFIG_INT("Screen", "default_height", "Default Height",
        &g_config.screen.defaultHeight, 0, 10000, OnConfigChange));

    // === Asset ===
    r.push_back(CONFIG_INT("Asset", "meme_placeholder_w", "Meme Placeholder W",
        &g_config.asset.memePlaceholderW, 0, 1000, OnConfigChange));
    r.push_back(CONFIG_INT("Asset", "meme_placeholder_h", "Meme Placeholder H",
        &g_config.asset.memePlaceholderH, 0, 1000, OnConfigChange));
    r.push_back(CONFIG_INT("Asset", "text_placeholder_w", "Text Placeholder W",
        &g_config.asset.textPlaceholderW, 0, 1000, OnConfigChange));
    r.push_back(CONFIG_INT("Asset", "text_placeholder_h", "Text Placeholder H",
        &g_config.asset.textPlaceholderH, 0, 1000, OnConfigChange));
    r.push_back(CONFIG_INT("Asset", "note_placeholder_w", "Note Placeholder W",
        &g_config.asset.notePlaceholderW, 0, 1000, OnConfigChange));
    r.push_back(CONFIG_INT("Asset", "note_placeholder_h", "Note Placeholder H",
        &g_config.asset.notePlaceholderH, 0, 1000, OnConfigChange));

    // === Cursor ===
    r.push_back(CONFIG_BOOL("Cursor", "chase_enabled", "Chase Enabled",
        &g_config.cursor.chaseEnabled, OnConfigChange));
    r.push_back(CONFIG_INT("Cursor", "chase_chance", "Chase Chance",
        &g_config.cursor.chaseChance, 0, 100, OnConfigChange));
    r.push_back(CONFIG_BOOL("Cursor", "multi_monitor_enabled", "Multi Monitor Enabled",
        &g_config.cursor.multiMonitorEnabled, OnConfigChange));

    // === Movement ===
    r.push_back(CONFIG_FLOAT("Movement", "base_walk_speed", "Base Walk Speed",
        &g_config.movement.baseWalkSpeed, 0.0f, 1000.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "base_run_speed", "Base Run Speed",
        &g_config.movement.baseRunSpeed, 0.0f, 1000.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "max_force", "Max Force",
        &g_config.movement.maxForce, 0.0f, 1000.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "move_distance_threshold", "Move Distance Threshold",
        &g_config.movement.moveDistanceThreshold, 0.0f, 1000.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "friction", "Friction",
        &g_config.movement.friction, 0.0f, 1000.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "max_speed", "Max Speed",
        &g_config.movement.maxSpeed, 0.0f, 1000.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "run_speed_multiplier", "Run Speed Multiplier",
        &g_config.movement.runSpeedMultiplier, 0.0f, 10.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "init_direction_max", "Init Direction Max",
        &g_config.movement.initDirectionMax, 0.0f, 360.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "speed_lerp_rate", "Speed Lerp Rate",
        &g_config.movement.speedLerpRate, 0.0f, 1.0f, 0.01f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "arrival_radius", "Arrival Radius",
        &g_config.movement.arrivalRadius, 0.0f, 1000.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "run_distance_threshold", "Run Distance Threshold",
        &g_config.movement.runDistanceThreshold, 0.0f, 2000.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Movement", "direction_blend_rate", "Direction Blend Rate",
        &g_config.movement.directionBlendRate, 0.0f, 1.0f, 0.01f, OnConfigChange));

    // === Physics ===
    r.push_back(CONFIG_FLOAT("Physics", "screen_margin", "Screen Margin",
        &g_config.physics.screenMargin, 0.0f, 500.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "bounce_factor_wall", "Bounce Factor Wall",
        &g_config.physics.bounceFactorWall, 0.0f, 2.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "bounce_factor_corner", "Bounce Factor Corner",
        &g_config.physics.bounceFactorCorner, 0.0f, 2.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "corner_margin", "Corner Margin",
        &g_config.physics.cornerMargin, 0.0f, 500.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "drag_min_dt", "Drag Min Dt",
        &g_config.physics.dragMinDt, 0.0f, 1.0f, 0.01f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "drag_velocity_threshold", "Drag Velocity Threshold",
        &g_config.physics.dragVelocityThreshold, 0.0f, 1000.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "drag_rotation_speed", "Drag Rotation Speed",
        &g_config.physics.dragRotationSpeed, 0.0f, 10.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "iso_scale_x", "Iso Scale X",
        &g_config.physics.isoScaleX, 0.1f, 2.0f, 0.01f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "iso_scale_y", "Iso Scale Y",
        &g_config.physics.isoScaleY, 0.1f, 2.0f, 0.01f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "edge_avoid_margin", "Edge Avoid Margin",
        &g_config.physics.edgeAvoidMargin, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "edge_look_ahead_speed", "Edge Look Ahead Speed",
        &g_config.physics.edgeLookAheadSpeed, 0.0f, 1.0f, 0.01f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "edge_look_ahead_base", "Edge Look Ahead Base",
        &g_config.physics.edgeLookAheadBase, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "edge_avoid_force", "Edge Avoid Force",
        &g_config.physics.edgeAvoidForce, 0.0f, 10.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "screen_clamp_tight", "Screen Clamp Tight",
        &g_config.physics.screenClampTight, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "screen_clamp_expanded", "Screen Clamp Expanded",
        &g_config.physics.screenClampExpanded, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "screen_clamp_bounce", "Screen Clamp Bounce",
        &g_config.physics.screenClampBounce, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "steer_seek_force", "Steer Seek Force",
        &g_config.physics.steerSeekForce, 0.0f, 20.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "curve_fade_distance", "Curve Fade Distance",
        &g_config.physics.curveFadeDistance, 0.0f, 1000.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "curve_tangent_force", "Curve Tangent Force",
        &g_config.physics.curveTangentForce, 0.0f, 5.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "curve_fade_min_vel", "Curve Fade Min Vel",
        &g_config.physics.curveFadeMinVel, 0.0f, 100.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "direction_rotate_min_vel", "Direction Rotate Min Vel",
        &g_config.physics.directionRotateMinVel, 0.0f, 100.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "direction_to_cursor_dist", "Direction To Cursor Dist",
        &g_config.physics.directionToCursorDist, 0.0f, 10.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "snap_distance", "Snap Distance",
        &g_config.physics.snapDistance, 0.0f, 10.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "direction_reverse_multiplier", "Direction Reverse Multiplier",
        &g_config.physics.directionReverseMultiplier, -1.0f, 1.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Physics", "min_valid_scale", "Min Valid Scale",
        &g_config.physics.minValidScale, 0.0f, 1.0f, 0.01f, OnConfigChange));

    // === Spawn ===
    r.push_back(CONFIG_FLOAT("Spawn", "margin_x", "Margin X",
        &g_config.spawn.marginX, 0.0f, 1000.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Spawn", "margin_y", "Margin Y",
        &g_config.spawn.marginY, 0.0f, 1000.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Spawn", "target_reached_threshold_return", "Target Reached Threshold Return",
        &g_config.spawn.targetReachedThresholdReturn, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Spawn", "target_reached_threshold_normal", "Target Reached Threshold Normal",
        &g_config.spawn.targetReachedThresholdNormal, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Spawn", "item_pickup_distance", "Item Pickup Distance",
        &g_config.spawn.itemPickupDistance, 0.0f, 100.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Spawn", "fetch_edge_margin", "Fetch Edge Margin",
        &g_config.spawn.fetchEdgeMargin, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Spawn", "separation_max_distance", "Separation Max Distance",
        &g_config.spawn.separationMaxDistance, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Spawn", "separation_force_multiplier", "Separation Force Multiplier",
        &g_config.spawn.separationForceMultiplier, 0.0f, 5.0f, 0.1f, OnConfigChange));

    // === Rig ===
    r.push_back(CONFIG_FLOAT("Rig", "body_y", "Body Y",
        &g_config.rig.bodyY, 0.0f, 50.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Rig", "neck_height_idle", "Neck Height Idle",
        &g_config.rig.neckHeightIdle, 0.0f, 50.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Rig", "neck_height_moving", "Neck Height Moving",
        &g_config.rig.neckHeightMoving, 0.0f, 50.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Rig", "beak_len", "Beak Length",
        &g_config.rig.beakLen, 0.0f, 30.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Rig", "beak_width", "Beak Width",
        &g_config.rig.beakWidth, 0.0f, 30.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Rig", "stride_max", "Stride Max",
        &g_config.rig.strideMax, 0.0f, 30.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Rig", "step_lift_height", "Step Lift Height",
        &g_config.rig.stepLiftHeight, 0.0f, 20.0f, 1.0f, OnConfigChange));

    // === Snatch ===
    r.push_back(CONFIG_FLOAT("Snatch", "radius_base", "Radius Base",
        &g_config.snatch.radiusBase, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Snatch", "radius_range", "Radius Range",
        &g_config.snatch.radiusRange, 0.0f, 200.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Snatch", "angular_speed_base", "Angular Speed Base",
        &g_config.snatch.angularSpeedBase, 0.0f, 10.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Snatch", "duration", "Duration",
        &g_config.snatch.duration, 0.0f, 10.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Snatch", "pull_distance", "Pull Distance",
        &g_config.snatch.pullDistance, 0.0f, 300.0f, 1.0f, OnConfigChange));

    // === Mud ===
    r.push_back(CONFIG_BOOL("Mud", "mud_enabled", "Mud Enabled",
        &g_config.mud.enabled, OnConfigChange));
    r.push_back(CONFIG_INT("Mud", "mud_chance", "Mud Chance",
        &g_config.mud.chance, 0, 100, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Mud", "mud_lifetime", "Mud Lifetime",
        &g_config.mud.lifetime, 0.0f, 60.0f, 1.0f, OnConfigChange));

    // === Honk ===
    r.push_back(CONFIG_FLOAT("Honk", "honk_min_gap", "Honk Min Gap",
        &g_config.honk.minGap, 0.0f, 5.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Honk", "honk_idle_min", "Honk Idle Min",
        &g_config.honk.idleMin, 0.0f, 30.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Honk", "honk_idle_max", "Honk Idle Max",
        &g_config.honk.idleMax, 0.0f, 60.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Honk", "honk_chase_cooldown", "Honk Chase Cooldown",
        &g_config.honk.chaseCooldown, 0.0f, 5.0f, 0.1f, OnConfigChange));

    // === Step ===
    r.push_back(CONFIG_FLOAT("Step", "step_time_fetch", "Step Time Fetch",
        &g_config.step.timeFetch, 0.0f, 1.0f, 0.01f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Step", "step_time_wander", "Step Time Wander",
        &g_config.step.timeWander, 0.0f, 1.0f, 0.01f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Step", "step_duration_walk", "Step Duration Walk",
        &g_config.step.durationWalk, 0.0f, 1.0f, 0.01f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Step", "step_duration_run", "Step Duration Run",
        &g_config.step.durationRun, 0.0f, 1.0f, 0.01f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Step", "step_lift_walk", "Step Lift Walk",
        &g_config.step.liftWalk, 0.0f, 20.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Step", "step_lift_run", "Step Lift Run",
        &g_config.step.liftRun, 0.0f, 20.0f, 1.0f, OnConfigChange));

    // === Item ===
    r.push_back(CONFIG_FLOAT("Item", "item_pickup_cooldown", "Item Pickup Cooldown",
        &g_config.item.pickupCooldown, 0.0f, 10.0f, 0.1f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Item", "item_lifetime", "Item Lifetime",
        &g_config.item.itemLifetime, 0.0f, 120.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Item", "meme_lifetime", "Meme Lifetime",
        &g_config.item.memeLifetime, 0.0f, 120.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Item", "text_lifetime", "Text Lifetime",
        &g_config.item.textLifetime, 0.0f, 120.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_INT("Item", "max_dropped_memes", "Max Dropped Memes",
        &g_config.item.maxDroppedMemes, 0, 100, OnConfigChange));
    r.push_back(CONFIG_INT("Item", "max_dropped_texts", "Max Dropped Texts",
        &g_config.item.maxDroppedTexts, 0, 100, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Item", "item_fetch_cooldown", "Item Fetch Cooldown",
        &g_config.item.fetchCooldown, 0.0f, 30.0f, 1.0f, OnConfigChange));

    // === Render ===
    r.push_back(CONFIG_FLOAT("Render", "shadow_offset_x", "Shadow Offset X",
        &g_config.render.shadowOffsetX, -20.0f, 20.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "shadow_offset_y", "Shadow Offset Y",
        &g_config.render.shadowOffsetY, 0.0f, 50.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "shadow_width", "Shadow Width",
        &g_config.render.shadowWidth, 0.0f, 100.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "shadow_height", "Shadow Height",
        &g_config.render.shadowHeight, 0.0f, 100.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "foot_size", "Foot Size",
        &g_config.render.footSize, 0.0f, 30.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "body_width", "Body Width",
        &g_config.render.bodyWidth, 0.0f, 50.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "body_height", "Body Height",
        &g_config.render.bodyHeight, 0.0f, 50.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "neck_size", "Neck Size",
        &g_config.render.neckSize, 0.0f, 30.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "head1_size", "Head 1 Size",
        &g_config.render.head1Size, 0.0f, 30.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "head2_size", "Head 2 Size",
        &g_config.render.head2Size, 0.0f, 30.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "eye_size", "Eye Size",
        &g_config.render.eyeSize, 0.0f, 20.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "click_radius", "Click Radius",
        &g_config.render.clickRadius, 0.0f, 100.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "footprint_width", "Footprint Width",
        &g_config.render.footprintWidth, 0.0f, 30.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "footprint_height", "Footprint Height",
        &g_config.render.footprintHeight, 0.0f, 30.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "close_button_size", "Close Button Size",
        &g_config.render.closeButtonSize, 0.0f, 50.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "text_note_font_size", "Text Note Font Size",
        &g_config.render.textNoteFontSize, 0.0f, 48.0f, 1.0f, OnConfigChange));
    r.push_back(CONFIG_FLOAT("Render", "squash_factor", "Squash Factor",
        &g_config.render.squashFactor, 0.5f, 1.0f, 0.01f, OnConfigChange));
}

